// Common disposable / temporary email domains. Not exhaustive but covers the main offenders.
const DISPOSABLE_DOMAINS = new Set<string>([
  "10minutemail.com", "10minutemail.net", "20minutemail.com",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.biz", "guerrillamail.de", "guerrillamailblock.com", "sharklasers.com", "grr.la",
  "mailinator.com", "mailinator.net", "mailinator.org", "mailinator2.com",
  "tempmail.com", "tempmail.net", "tempmail.org", "tempmailo.com", "temp-mail.org", "temp-mail.io", "tmpmail.org", "tmpmail.net", "tmpeml.com",
  "yopmail.com", "yopmail.fr", "yopmail.net",
  "throwawaymail.com", "throwawayemail.com",
  "trashmail.com", "trashmail.net", "trashmail.de", "trash-mail.com",
  "fakeinbox.com", "fake-mail.net", "fakemail.net",
  "getairmail.com", "getnada.com", "nada.email",
  "maildrop.cc", "mailcatch.com", "mailtemp.info", "mailmoat.com",
  "dispostable.com", "spambog.com", "spambog.de", "spambog.ru",
  "discard.email", "discardmail.com", "discardmail.de",
  "emailondeck.com", "instant-mail.de", "mintemail.com", "moakt.com",
  "mt2015.com", "owlpic.com", "spamgourmet.com", "tempinbox.com",
  "tempr.email", "tmail.ws", "tmails.net", "wegwerfmail.de",
  "harakirimail.com", "incognitomail.com", "mvrht.net",
  "mohmal.com", "boun.cr", "bouncr.com", "deadaddress.com",
  "anonbox.net", "anonymbox.com", "byom.de", "spam4.me",
  "33mail.com", "armyspy.com", "cuvox.de", "dayrep.com",
  "einrot.com", "fleckens.hu", "gustr.com", "jourrapide.com",
  "rhyta.com", "superrito.com", "teleworm.us",
  "0-mail.com", "0815.ru", "0clickemail.com", "10x.es",
  "33mail.com", "5ymail.com", "60minutemail.com",
  "anonymbox.com", "antichef.com", "antichef.net", "antispam.de",
  "binkmail.com", "bobmail.info", "bofthew.com", "brefmail.com",
  "bsnow.net", "bspamfree.org", "bugmenot.com",
  "cellurl.com", "chogmail.com", "choicemail1.com", "clrmail.com",
  "cool.fr.nf", "courriel.fr.nf", "courrieltemporaire.com",
  "curryworld.de", "cust.in", "dacoolest.com",
  "deadfake.cf", "deadfake.ga", "deadfake.ml", "deadfake.tk",
  "dharmatel.net", "dingbone.com", "disposableaddress.com",
  "dontreg.com", "dontsendmespam.de", "drdrb.net",
  "dudmail.com", "easytrashmail.com", "edv.to",
  "email60.com", "emailgo.de", "emailias.com",
  "emailigo.de", "emailinfive.com", "emailisvalid.com",
  "emailmiser.com", "emailsensei.com", "emailtemporanea.com",
  "emailtemporanea.net", "emailtemporario.com.br", "emailtmp.com",
  "emailto.de", "emailwarden.com", "emailx.at.hm",
  "emailxfer.com", "emeil.in", "emeil.ir",
  "emz.net", "evopo.com", "explodemail.com",
  "fakemailgenerator.com", "fakemailz.com", "fastacura.com",
  "fastchevy.com", "fastchrysler.com", "fastkawasaki.com",
  "fastmazda.com", "fastmitsubishi.com", "fastnissan.com",
  "fastsubaru.com", "fastsuzuki.com", "fasttoyota.com",
  "fastyamaha.com", "filzmail.com", "fizmail.com",
  "fr33mail.info", "frapmail.com", "front14.org", "fux0ringduh.com",
  "garliclife.com", "get1mail.com", "get2mail.fr", "ge.tt",
  "getairmail.cf", "getairmail.ga", "getairmail.gq", "getairmail.ml", "getairmail.tk",
  "getmails.eu", "ghosttexter.de", "girlsundertheinfluence.com",
  "gishpuppy.com", "gmial.com", "great-host.in",
  "greggamel.com", "gsrv.co.uk", "guerillamail.biz", "guerillamail.com",
  "h.mintemail.com", "haltospam.com", "hatespam.org",
  "hidemail.de", "hochsitze.com", "hotpop.com",
  "hulapla.de", "ieatspam.eu", "ieatspam.info",
  "ihateyoualot.info", "iheartspam.org", "ikbenspamvrij.nl",
  "imails.info", "inboxalias.com", "inboxclean.com",
  "inboxclean.org", "incognitomail.net", "incognitomail.org",
  "ipoo.org", "irish2me.com", "iwi.net",
  "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
  "jnxjn.com", "junk1e.com", "kasmail.com",
  "kaspop.com", "keepmymail.com", "killmail.com", "killmail.net",
  "kir.ch.tc", "klassmaster.com", "klzlk.com",
  "kostenlosemailadresse.de", "kulturbetrieb.info", "kurzepost.de",
  "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
  "link2mail.net", "litedrop.com", "lol.ovpn.to",
  "lookugly.com", "lortemail.dk", "lroid.com",
  "lukop.dk", "m21.cc", "mailbidon.com",
  "mailbiz.biz", "mailblocks.com", "mailbucket.org",
  "mailde.de", "mailde.info", "maileater.com",
  "mailexpire.com", "mailfa.tk", "mailforspam.com",
  "mailfreeonline.com", "mailguard.me", "mailin8r.com",
  "mailinator.gq", "mailinator2.net", "mailincubator.com",
  "mailme.lv", "mailme24.com", "mailmetrash.com",
  "mailmoat.com", "mailms.com", "mailnesia.com",
  "mailnull.com", "mailpick.biz", "mailrock.biz",
  "mailscrap.com", "mailshell.com", "mailsiphon.com",
  "mailtome.de", "mailtothis.com", "mailtrash.net",
  "mailtv.net", "mailtv.tv", "mailzilla.com",
  "makemetheking.com", "manybrain.com", "mbx.cc",
  "mega.zik.dj", "meinspamschutz.de", "meltmail.com",
  "messagebeamer.de", "mierdamail.com", "mintemail.com",
  "mjukglass.nu", "mobi.web.id", "moburl.com",
  "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
  "msa.minsmail.com", "mt2009.com", "mx0.wwwnew.eu",
  "mycard.net.ua", "mycleaninbox.net", "mymail-in.net",
  "mypartyclip.de", "myphantomemail.com", "mysamp.de",
  "mytempemail.com", "mytempmail.com", "mytrashmail.com",
  "neomailbox.com", "nepwk.com", "nervmich.net",
  "nervtmich.net", "netmails.com", "netmails.net",
  "netzidiot.de", "neverbox.com", "nice-4u.com",
  "nincsmail.hu", "nnh.com", "no-spam.ws",
  "noblepioneer.com", "nomail.xl.cx", "nomail2me.com",
  "nomorespamemails.com", "nospam.ze.tc", "nospam4.us",
  "nospamfor.us", "nospamthanks.info", "notmailinator.com",
  "nowmymail.com", "nurfuerspam.de", "nus.edu.sg",
  "nwldx.com", "objectmail.com", "obobbo.com",
  "odaymail.com", "oneoffemail.com", "onewaymail.com",
  "online.ms", "oopi.org", "ordinaryamerican.net",
  "otherinbox.com", "ourklips.com", "outlawspam.com",
  "ovpn.to", "owlpic.com", "pancakemail.com",
  "pjjkp.com", "plexolan.de", "poczta.onet.pl",
  "politikerclub.de", "poofy.org", "pookmail.com",
  "privacy.net", "privatdemail.net", "proxymail.eu",
  "prtnx.com", "punkass.com", "putthisinyourspamdatabase.com",
  "pwrby.com", "quickinbox.com", "rcpt.at",
  "reallymymail.com", "realtyalerts.ca", "recode.me",
  "recursor.net", "regbypass.com", "regbypass.comsafe-mail.net",
  "rejectmail.com", "reliable-mail.com", "rhyta.com",
  "rmqkr.net", "royal.net", "rppkn.com",
  "rtrtr.com", "s0ny.net", "safe-mail.net",
  "safersignup.de", "safetymail.info", "safetypost.de",
  "sandelf.de", "saynotospams.com", "schafmail.de",
  "schrott-email.de", "secretemail.de", "secure-mail.biz",
  "selfdestructingmail.com", "sendspamhere.com", "sharedmailbox.org",
  "shieldedmail.com", "shiftmail.com", "shitmail.me",
  "shitmail.org", "shortmail.net", "showslow.com",
  "sibmail.com", "sinnlos-mail.de", "siteposter.net",
  "skeefmail.com", "slaskpost.se", "smashmail.de",
  "smellfear.com", "snakemail.com", "sneakemail.com",
  "sofimail.com", "sofort-mail.de", "softpls.asia",
  "sogetthis.com", "soodonims.com", "spam.la",
  "spam.su", "spamavert.com", "spambob.com",
  "spambob.net", "spambob.org", "spambox.info",
  "spambox.irishspringrealty.com", "spambox.us", "spamcero.com",
  "spamcon.org", "spamcorptastic.com", "spamcowboy.com",
  "spamcowboy.net", "spamcowboy.org", "spamday.com",
  "spamex.com", "spamfree24.com", "spamfree24.de",
  "spamfree24.eu", "spamfree24.info", "spamfree24.net",
  "spamfree24.org", "spamhereplease.com", "spamhole.com",
  "spamify.com", "spaminator.de", "spamkill.info",
  "spaml.com", "spaml.de", "spammotel.com",
  "spamobox.com", "spamoff.de", "spamslicer.com",
  "spamspot.com", "spamthis.co.uk", "spamthisplease.com",
  "spamtrail.com", "speed.1s.fr", "ssoia.com",
  "stinkefinger.net", "stuffmail.de", "supergreatmail.com",
  "supermailer.jp", "suremail.info", "talkinator.com",
  "tapchicuoihoi.com", "teewars.org", "teleosaurs.xyz",
  "teleworm.com", "tempalias.com", "tempe-mail.com",
  "tempemail.biz", "tempemail.com", "tempemail.net",
  "tempinbox.co.uk", "tempinbox.com", "tempmail.eu",
  "tempmail2.com", "tempmaildemo.com", "tempmailer.com",
  "tempmailer.de", "tempomail.fr", "tempymail.com",
  "thanksnospam.info", "thankyou2010.com", "thc.st",
  "thecloudindex.com", "thisisnotmyrealemail.com", "throwam.com",
  "throwawayemailaddress.com", "tilien.com", "tittbit.in",
  "tizi.com", "tmailinator.com", "toiea.com",
  "tradermail.info", "trash2009.com", "trash2010.com",
  "trash2011.com", "trash-amil.com", "trashemail.de",
  "trashmail.at", "trashmail.io", "trashmail.me",
  "trashmail.ws", "trashymail.com", "trashymail.net",
  "trbvm.com", "trialmail.de", "trillianpro.com",
  "twinmail.de", "tyldd.com", "uggsrock.com",
  "umail.net", "uroid.com", "us.af",
  "venompen.com", "veryrealemail.com", "viditag.com",
  "viralplays.com", "vpn.st", "vsimcard.com",
  "vubby.com", "wasteland.rfc822.org", "webemail.me",
  "webm4il.info", "wegwerf-emails.de", "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de", "wegwerfmail.info",
  "wegwerfmail.net", "wegwerfmail.org", "wh4f.org",
  "whatpaas.com", "whyspam.me", "willhackforfood.biz",
  "willselfdestruct.com", "winemaven.info", "wronghead.com",
  "wuzup.net", "wuzupmail.net", "www.e4ward.com",
  "www.gishpuppy.com", "www.mailinator.com", "wwwnew.eu",
  "x.ip6.li", "xagloo.com", "xemaps.com",
  "xents.com", "xmaily.com", "xoxy.net",
  "yapped.net", "yeah.net", "yep.it",
  "yogamaven.com", "yougotgoated.com", "yuurok.com",
  "zehnminuten.de", "zehnminutenmail.de", "zippymail.info",
  "zoaxe.com", "zoemail.org", "zomg.info",
]);

export function isDisposableEmail(email: string): boolean {
  const at = email.lastIndexOf("@");
  if (at < 0) return true;
  const domain = email.slice(at + 1).toLowerCase().trim();
  return DISPOSABLE_DOMAINS.has(domain);
}
