// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-layouts/FloatingCards.tsx": () => import("../components/mockups/hero-layouts/FloatingCards.tsx"),
  "./components/mockups/hero-layouts/Glassmorphism.tsx": () => import("../components/mockups/hero-layouts/Glassmorphism.tsx"),
  "./components/mockups/hero-layouts/NewsTicker.tsx": () => import("../components/mockups/hero-layouts/NewsTicker.tsx"),
  "./components/mockups/hero-layouts/SplitScreen.tsx": () => import("../components/mockups/hero-layouts/SplitScreen.tsx"),
  "./components/mockups/hero-layouts/TerminalHacker.tsx": () => import("../components/mockups/hero-layouts/TerminalHacker.tsx"),
  "./components/mockups/hero-layouts/UltraMinimal.tsx": () => import("../components/mockups/hero-layouts/UltraMinimal.tsx"),
  "./components/mockups/themes/Cyberpunk.tsx": () => import("../components/mockups/themes/Cyberpunk.tsx"),
  "./components/mockups/themes/EmeraldDark.tsx": () => import("../components/mockups/themes/EmeraldDark.tsx"),
  "./components/mockups/themes/LuxeMinimal.tsx": () => import("../components/mockups/themes/LuxeMinimal.tsx"),
  "./components/mockups/themes/MidnightBlue.tsx": () => import("../components/mockups/themes/MidnightBlue.tsx"),
  "./components/mockups/product-cards/HoloCard.tsx": () => import("../components/mockups/product-cards/HoloCard.tsx"),
  "./components/mockups/product-cards/MinimalApple.tsx": () => import("../components/mockups/product-cards/MinimalApple.tsx"),
  "./components/mockups/product-cards/NeonGaming.tsx": () => import("../components/mockups/product-cards/NeonGaming.tsx"),
  "./components/mockups/product-cards/PremiumGlass.tsx": () => import("../components/mockups/product-cards/PremiumGlass.tsx"),
  "./components/mockups/wallet-layouts/CompactDark.tsx": () => import("../components/mockups/wallet-layouts/CompactDark.tsx"),
  "./components/mockups/wallet-layouts/NeonDashboard.tsx": () => import("../components/mockups/wallet-layouts/NeonDashboard.tsx"),
  "./components/mockups/wallet-layouts/PremiumCard.tsx": () => import("../components/mockups/wallet-layouts/PremiumCard.tsx"),
  "./components/mockups/wallet-layouts/logos.tsx": () => import("../components/mockups/wallet-layouts/logos.tsx")
};
