// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/product-cards/HoloCard.tsx": () => import("../components/mockups/product-cards/HoloCard.tsx"),
  "./components/mockups/product-cards/MinimalApple.tsx": () => import("../components/mockups/product-cards/MinimalApple.tsx"),
  "./components/mockups/product-cards/NeonGaming.tsx": () => import("../components/mockups/product-cards/NeonGaming.tsx"),
  "./components/mockups/product-cards/PremiumGlass.tsx": () => import("../components/mockups/product-cards/PremiumGlass.tsx")
};
